version: "3.1"

services:
  spring:
    build:
      context: ./backend
      dockerfile: Dockerfile
    hostname: spring
    ports:
      - 8082:8082
      - 8001:8001
    restart: "no"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/storagedb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    container_name: storage-spring

  db:
    image: postgres:9.6.24
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: storagedb
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432 
    volumes:
      - ./data/db:/var/lib/postgresql/data
    container_name: storage-postgres

  adminer:
    image: adminer
    ports:
      - 8080:8080
    container_name: storage-adminer